# Generated by Django 2.0.1 on 2018-04-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user_profile_model',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
