# Generated by Django 2.0.1 on 2018-04-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_trainer', '0002_auto_20180402_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
