# Generated by Django 2.0.1 on 2018-04-03 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strength_trainer', '0003_auto_20180402_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewWorkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_squat', models.PositiveIntegerField(default=None)),
                ('max_bench', models.PositiveIntegerField(default=None)),
                ('max_deadlift', models.PositiveIntegerField(default=None)),
                ('max_overhead', models.PositiveIntegerField(default=None)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
