# Generated by Django 2.0.1 on 2018-04-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength_trainer', '0004_newworkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('bench', models.CharField(max_length=250)),
                ('bench_done', models.BooleanField(default=False)),
                ('squat', models.CharField(max_length=250)),
                ('sqaut_done', models.BooleanField(default=False)),
                ('deadlift', models.CharField(max_length=250)),
                ('deadlift_done', models.BooleanField(default=False)),
                ('overhead', models.CharField(max_length=250)),
                ('overhead_done', models.BooleanField(default=False)),
                ('associated_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strength_trainer.NewWorkout')),
            ],
        ),
    ]
