# Generated by Django 2.0.1 on 2018-04-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_trainer', '0006_auto_20180415_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutweek',
            name='prettyName',
            field=models.CharField(default='week 1', max_length=250),
            preserve_default=False,
        ),
    ]
