# Generated by Django 2.0.1 on 2018-04-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength_trainer', '0007_workoutweek_prettyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutweek',
            name='reps',
            field=models.CharField(default='5/5/5', max_length=250),
            preserve_default=False,
        ),
    ]
